image: Visual Studio 2022
version: '{branch}-{build}'
init:
- cmd: git config --global core.autocrlf true
before_build:
    - dotnet tool update -g docfx
    - choco install chromedriver
    - cmd: PATH=C:\ProgramData\chocolatey\lib\chromedriver\tools\chromedriver-win32;%PATH%
    - cmd: dir C:\ProgramData\chocolatey\lib\chromedriver\tools\chromedriver-win32
build_script:
    - dotnet build
    - docfx CSF.Extensions.WebDriver.Docs\docfx.json
test_script:
    - dotnet test
