sudo: false
language: csharp
solution: CSF.WebDriverExtras.sln

addons:
  sauce_connect:
    direct_domains: google.com

env:
  - WebDriver_Platform="Windows 10"
  - WebDriver_BrowserName="Chrome"

install: Tools/Travis.install.sh

script: Tools/Travis.build.sh